[antlir2][features] add oci_label feature
Summary:
Track OCI container labels via antlir features so that can be added
layer-by-layer and composed together in the final package

Test Plan:
```
❯ buck2 test fbcode//antlir/antlir2/test_images/package/oci/...
Buck UI: https://www.internalfb.com/buck2/08110de6-6e21-4404-b0c8-da922d765f89
Test UI: https://www.internalfb.com/intern/testinfra/testrun/15762598837714692
Tests finished: Pass 3. Fail 0. Fatal 0. Skip 0. Omit 0. Infra Failure 0. Build failure 0
```

intentionally break by duplicating a label key
```counterexample
❯ hg diff
 diff --git a/fbcode/antlir/antlir2/test_images/package/oci/BUCK b/fbcode/antlir/antlir2/test_images/package/oci/BUCK
 --- a/fbcode/antlir/antlir2/test_images/package/oci/BUCK
+++ b/fbcode/antlir/antlir2/test_images/package/oci/BUCK
@@ -30,6 +30,10 @@
     name = "intermediate",
     features = [
         feature.remove(path = "/to-be-deleted-and-recreated"),
+        oci_features.label(
+            key = "com.meta.test.label",
+            value = "bad-duplicated-label",
+        ),
     ],
     parent_layer = ":base",
 )

❯ buck2 test fbcode//antlir/antlir2/test_images/package/oci/...
Action failed: fbcode//antlir/antlir2/test_images/package/oci:oci (antlir2_package oci)
Local command returned non-zero exit code 1
Reproduce locally: `env --chdir="$(buck2 root --kind project)" -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/d2033bf939e4 ...<omitted>... ec=buck-out/v2/gen/fbcode/f92b285dc4da35b4/antlir/antlir2/test_images/package/oci/__oci__/spec.json' (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
Error: duplicate label 'com.meta.test.label', already set to 'bad-duplicated-label'
```

Reviewed By: liubov-dmitrieva

Differential Revision: D90786760

fbshipit-source-id: 4b74ceb9b1457ee422bb38cfd6ee4629b19018a4