[antlir] Fix Python shapes test
Summary:
The [test](https://fburl.com/test/hiatysoi) has been failing for a while probably because of some changes in Python frozen dicts

```
[dubros@devbig006.eag3 /data/users/dubros/fbsource (7cc3bbb930)]$ buck test fbcode//antlir/bzl/tests/shapes/... -- --run-disabled
File changed: fbcode//antlir/bzl/tests/shapes/BUCK
✗ Fail: fbcode//antlir/bzl/tests/shapes:test-shape - test_data_and_resources (antlir.bzl.tests.shapes.test_shape.TestShape) (0.0s)

test_data_and_resources (antlir.bzl.tests.shapes.test_shape.TestShape) ... ERROR

======================================================================
ERROR: test_data_and_resources (antlir.bzl.tests.shapes.test_shape.TestShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/dubros/fbsource/buck-out/v2/gen/fbcode/b2adfdf9e0a81ff7/antlir/bzl/tests/shapes/__test-shape__/test-shape#link-tree/antlir/bzl/tests/shapes/test_shape.py", line 74, in test_data_and_resources
    self.assertEqual(imp, res)
  File "/usr/local/fbcode/platform010/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/fbcode/platform010/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
  File "/data/users/dubros/fbsource/buck-out/v2/gen/fbcode/b2adfdf9e0a81ff7/antlir/bzl/tests/shapes/__test-shape__/test-shape#link-tree/pydantic/v1/main.py", line 913, in __eq__
    return self.dict() == other.dict()
           ^^^^^^^^^^^
  File "/data/users/dubros/fbsource/buck-out/v2/gen/fbcode/b2adfdf9e0a81ff7/antlir/bzl/tests/shapes/__test-shape__/test-shape#link-tree/pydantic/v1/main.py", line 455, in dict
    return dict(
           ^^^^^
  File "/data/users/dubros/fbsource/buck-out/v2/gen/fbcode/b2adfdf9e0a81ff7/antlir/bzl/tests/shapes/__test-shape__/test-shape#link-tree/pydantic/v1/main.py", line 872, in _iter
    v = self._get_value(
        ^^^^^^^^^^^^^^^^
  File "/data/users/dubros/fbsource/buck-out/v2/gen/fbcode/b2adfdf9e0a81ff7/antlir/bzl/tests/shapes/__test-shape__/test-shape#link-tree/pydantic/v1/main.py", line 799, in _get_value
    return v.__class__(*seq_args) if is_namedtuple(v.__class__) else v.__class__(seq_args)
                                                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/dubros/fbsource/buck-out/v2/gen/fbcode/b2adfdf9e0a81ff7/antlir/bzl/tests/shapes/__test-shape__/test-shape#link-tree/antlir/freeze.py", line 38, in __new__
    return tuple.__new__(cls, (MappingProxyType(dict(*args, **kwargs)),))
                                                ^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 7; 2 is required
```

Test Plan:
```
$ buck test fbcode//antlir/bzl/tests/shapes/... -- --run-disabled
Buck UI: https://www.internalfb.com/buck2/fbdf12a7-b5ba-4387-b8e4-8157b5912f24
Test UI: https://www.internalfb.com/intern/testinfra/testrun/14355223954829702
Network: Up: 0B  Down: 0B
Command: test.
Time elapsed: 2.1s
Tests finished: Pass 24. Fail 0. Fatal 0. Skip 0. Omit 0. Infra Failure 0. Build failure 0
```

```
$ buck test fbcode//mode/opt -c 'fbcode.arch=aarch64' fbcode//antlir/bzl/tests/shapes:test-shape -- --exact 'fbcode//antlir/bzl/tests/shapes:test-shape - test_data_and_resources (antlir.bzl.tests.shapes.test_shape.TestShape)' --run-disabled
Buck UI: https://www.internalfb.com/buck2/17e0f196-a9d3-4972-844a-ae9d96a52d19
Test UI: https://www.internalfb.com/intern/testinfra/testrun/7881299673406306
Network: Up: 4.9MiB  Down: 7.4MiB  (reSessionID-d81e652f-9d40-4a32-b7a1-bf7dd7b1e3bf)
Loading targets.   Remaining     0/1021                                                      32027 dirs read, 36314 targets declared
Analyzing targets. Remaining     0/11532                                                     106721 actions, 160671 artifacts declared
Executing actions. Remaining     0/7881                                                      12:30.8s exec time total
Command: test.     Finished 9 local, 851 cache (99% hit)                                     12:27.2s exec time cached (99%)
Time elapsed: 17.1s
Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Omit 0. Infra Failure 0. Build failure 0
```

Reviewed By: elibus

Differential Revision: D90945996

fbshipit-source-id: 74568b91ff598cf36053f5a4f343c570fd509f02