[third-party/rust] Support uuid "rng-getrandom" feature
Summary:
X-link: https://github.com/meta-pytorch/monarch/pull/1688

Required in D85438479, which contains a handwritten Cargo.toml (fbcode/pyrefly/pyrefly_wasm/Cargo.toml) that gets incorporated into an Autocargo-generated Cargo.lock (fbcode/pyrefly/Cargo.lock).

In order for the handwritten Cargo.toml to be able to use uuid with "rng-getrandom", the Cargo.lock generation needs to have offline access to all the transitive dependencies pulled by this feature.

https://www.internalfb.com/code/fbsource/[0cc72b95913a155b4ae4b660196a25e4c23cd6b1]/fbcode/pyrefly/pyrefly_wasm/Cargo.toml?lines=17%2C26

Test Plan:
`arc autocargo -p pyrefly`

**Before:**

```lang=log,counterexample
10:08:55 -07:00 INFO Running 'generate_cargo_lock' for 'pyrefly'
Error: While running 'generate_cargo_lock' for 'pyrefly'

Caused by:
    no matching package named `uuid-rng-internal` found
    location searched: directory source `/data/users/dtolnay/fbsource/third-party/rust/vendor` (which is replacing registry `crates-io`)
    required by package `uuid v1.17.0`
        ... which satisfies dependency `uuid = "^1.17"` (locked to 1.17.0) of package `pyrefly_wasm v0.0.0 (/data/users/dtolnay/fbsource/fbcode/pyrefly/pyrefly_wasm)`
    As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without `--offline`
```

**After:** success.

Reviewed By: diliop

Differential Revision: D85680730

fbshipit-source-id: 34dc2e1882651056f4984a8618010afb0c8d1017