[antlir2][antlir2_change_stream] Use bounded channell to limit amount of open file descriptors
Summary:
Upstream fbpkg update triggered S597295 failure to build an oci image with
```
[2025-12-01T15:42:46.164-08:00] Action failed: fbcode//brioche/containers/host:host_centos9_image@1336b6fce9366170 (oci_layer fbpkg)
[2025-12-01T15:42:46.164-08:00] Local command returned non-zero exit code 1
[2025-12-01T15:42:46.164-08:00] Local command: env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp-anon/fbcode/49ab3769e6731fe8brioche/containers/host/1336b6fce9366170/__host_centos9_image__fbpkg/layer.tar__/oci_layer/fbpkg' buck-out/v2/gen/fbcode/49ab3769e6731fe8/antlir/antlir2/antlir2_packager/make_oci_layer/__make-oci-layer__/make_oci_layer --rootless '--parent=buck-out/v2/gen/fbcode/e10885b2eba62c12/bastille/containers/host/__host_centos9_base_image__/compile/subvol_symlink' '--child=buck-out/v2/gen/fbcode/e10885b2eba62c12/brioche/containers/host/__host_centos9_image__/fbpkg/subvol_symlink' '--out=buck-out/v2/gen-anon/fbcode/49ab3769e6731fe8brioche/containers/host/1336b6fce9366170/__host_centos9_image__/fbpkg/layer.tar'
[2025-12-01T15:42:46.164-08:00] Stdout: <empty>
[2025-12-01T15:42:46.164-08:00] Stderr:
Error: Too many open files (os error 24)
```
https://www.internalfb.com/sandcastle/job/18014400865789478

New fbpkg increased in size and amount of files. My theory is that more files, bigger files, directory composition slowed down consumer, increased the amount of NewFiles alive at the same time substantially

https://www.internalfb.com/code/fbsource/[e1aa050d4299]/fbcode/antlir/antlir2/antlir2_packager/make_oci_layer/src/main.rs?lines=70-77

and let producer fill the chanel with enough of **NewFile** structs.

https://www.internalfb.com/code/fbsource/[e1aa050d4299]/fbcode/antlir/antlir2/antlir2_change_stream/src/compare/tree.rs?lines=92-95

to overflow the **ulimit -n**.

Test Plan:
before:

added sleep(1) in
https://www.internalfb.com/code/fbsource/[e1aa050d4299]/fbcode/antlir/antlir2/antlir2_packager/make_oci_layer/src/main.rs?lines=70-77

 to force the consumer to slow down.
```
❯ ps axfw|grep 982890
1002053 pts/10   S+     0:00  |   \_ grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox 982890
 982890 ?        S      0:10      |   \_ /data/users/mge/fbsource/buck-out/v2/gen/fbcode/49ab3769e6731fe8/antlir/antlir2/antlir2_packager/make_oci_layer/__make-oci-layer__/make_oci_layer --rootless --parent=buck-out/v2/gen/fbcode/e10885b2eba62c12/bastille/containers/host/__host_centos9_base_image__/compile/subvol_symlink --child=buck-out/v2/gen/fbcode/e10885b2eba62c12/brioche/containers/host/__host_centos9_image__/fbpkg/subvol_symlink --out=buck-out/v2/gen-anon/fbcode/49ab3769e6731fe8brioche/containers/host/1336b6fce9366170/__host_centos9_image__/fbpkg/layer.tar

❯ cd buck-out/v2/gen/fbcode/e10885b2eba62c12/brioche/containers/host/__host_centos9_image__/fbpkg/subvol_symlink
❯ find -type f|wc -l
141367

❯ cd buck-out/v2/gen/fbcode/e10885b2eba62c12/bastille/containers/host/__host_centos9_base_image__/compile/subvol_symlink
cd: no such file or directory: buck-out/v2/gen/fbcode/e10885b2eba62c12/bastille/containers/host/__host_centos9_base_image__/compile/subvol_symlink
❯ cd ~/buck-out/v2/gen/fbcode/e10885b2eba62c12/bastille/containers/host/__host_centos9_base_image__/compile/subvol_symlink
❯ find -type f|wc -l
61067

141k-61k ~ 80k open files

❯ lsof -p 982890|wc -l
80322
```

after:
```
❯ lsof -p 1029159|wc -l
1130
```

Job run on commit with this change still failed:
https://www.internalfb.com/sandcastle/workflow/2463468996183679954

I'm not sure if it's because it's not the issue we see in prod or maybe it was not actually used for the build ?

Reviewed By: vmagro

Differential Revision: D88288021

fbshipit-source-id: abd156411ebf6b3f0920df3db57d5f35160bc6b7